### ISSUE TITLE
Resourcer doesn't successfully launch

### ISSUE THREAD

**Issue by nishanth1232** [HaikuArchives/Resourcer#4]
When resourcer is opened in Haiku, it shows up on the deskbar but does not open. When it is clicked on the deskbar, it says 'No windows'.

**Comment by anevilyak** [comment]
This appears to be because the app has hardcoded BeOS's temp directory (/boot/var/tmp) in its source rather than using find_directory to locate it. Since that's no longer the correct temp location on Haiku, creating an empty resource file to start a window for fails. 

Unfortunately, the app's response to this is to silently return from the window constructor, leading to the above situation of an app message loop running, but no visible windows.
